#=============================================================
# MonitoringServer Configuration
#=============================================================

[LanServer]
PORT            = 20000
MAX_SESSION     = 100

[NetServer]
PORT            = 21510
MAX_SESSION     = 200
PACKET_CODE     = 109
PACKET_KEY      = 30

[Database]
HOST            = 127.0.0.1
PORT            = 3306
USER            = root
PASSWORD        = vmfh1234!
DATABASE        = logdb

[Pool]
MAX_PACKET_POOL = 10000

[System]
LOG_DIRECTORY   = Log
LOG_LEVEL       = DEBUG
CONSOLE_OUTPUT  = false
